### ISSUE TITLE
TypeScript error: src/heightfield.ts(81,14): Error TS2532: Object is possibly 'undefined'.

### ISSUE THREAD

**Issue by MGPelloni** [spacejack/terra#1]
I'm continuing to get an error of "TypeScript error: src/heightfield.ts(81,14): Error TS2532: Object is possibly 'undefined'." when running npm start. I'm new at node so this might be an oversight on my part.

**Comment by spacejack** [comment]
Sorry, for some reason it looks like npm installs typescript 2.2.1 locally instead of 2.1.4. I've updated the package versions and made a fix so it compiles with the latest typescript. You'll need to run `npm install` again after pulling the latest. Thanks for the heads-up!
